express:
  host: localhost
  port: 8080

auth:
  jwt_secret:  'MySuperSecret!234'

mongo:
  connection_string:  'mongodb://91lyftdev:MySuperPassword@ds253918.mlab.com:53918/91lyft-dev'

loglevel: info